export const CLIENT_GET_REQUEST = 'CLIENT_GET_REQUEST'
export const CLIENT_GET_SUCCESS = 'CLIENT_GET_SUCCESS'
export const CLIENT_GET_FAIL = 'CLIENT_GET_FAIL'

export const CLIENT_ALL_GET_REQUEST = 'CLIENT_ALL_GET_REQUEST'
export const CLIENT_ALL_GET_SUCCESS = 'CLIENT_ALL_GET_SUCCESS'
export const CLIENT_ALL_GET_FAIL = 'CLIENT_ALL_GET_FAIL'
