// create event request
export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL'

// get event request by status
export const GET_EVENT_BY_STATUS_REQUEST = 'GET_EVENT_BY_STATUS_REQUEST'
export const GET_EVENT_BY_STATUS_SUCCESS = 'GET_EVENT_BY_STATUS_SUCCESS'
export const GET_EVENT_BY_STATUS_FAIL = 'GET_EVENT_BY_STATUS_FAIL'

// updating request status
export const UPDATE_EVENT_REQUEST_STATUS_REQUEST =
  'UPDATE_EVENT_REQUEST_STATUS_REQUEST'
export const UPDATE_EVENT_REQUEST_STATUS_SUCCESS =
  'UPDATE_EVENT_REQUEST_STATUS_SUCCESS'
export const UPDATE_EVENT_REQUEST_STATUS_FAIL =
  'UPDATE_EVENT_REQUEST_STATUS_FAIL'

// new event creation from event request after status approved for request
export const EVENT_REQUEST = 'EVENT_REQUEST'
export const EVENT_SUCCESS = 'EVENT_SUCCESS'
export const EVENT_FAIL = 'EVENT_FAIL'
