export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL'

export const GET_EVENT_BY_STATUS_REQUEST = 'GET_EVENT_BY_STATUS_REQUEST'
export const GET_EVENT_BY_STATUS_SUCCESS = 'GET_EVENT_BY_STATUS_SUCCESS'
export const GET_EVENT_BY_STATUS_FAIL = 'GET_EVENT_BY_STATUS_FAIL'
