export const EXTRA_BUDGET_REQUEST = 'EXTRA_BUDGET_REQUEST'
export const EXTRA_BUDGET_SUCCESS = 'EXTRA_BUDGET_SUCCESS'
export const EXTRA_BUDGET_FAIL = 'EXTRA_BUDGET_FAIL'

export const EXTRA_STAFF_REQUEST = 'EXTRA_STAFF_REQUEST'
export const EXTRA_STAFF_SUCCESS = 'EXTRA_STAFF_SUCCESS'
export const EXTRA_STAFF_FAIL = 'EXTRA_STAFF_FAIL'

export const GET_BUDGETS_REQUEST = 'GET_BUDGETS_REQUEST'
export const GET_BUDGETS_SUCCESS = 'GET_BUDGETS_SUCCESS'
export const GET_BUDGETS_FAIL = 'GET_BUDGETS_FAIL'

export const GET_STAFFS_REQUEST = 'GET_STAFFS_REQUEST'
export const GET_STAFFS_SUCCESS = 'GET_STAFFS_SUCCESS'
export const GET_STAFFS_FAIL = 'GET_STAFFS_FAIL'

export const UPDATE_BUDGET_REQUEST = 'UPDATE_BUDGET_REQUEST'
export const UPDATE_BUDGET_SUCCESS = 'UPDATE_BUDGET_SUCCESS'
export const UPDATE_BUDGET_FAIL = 'UPDATE_BUDGET_FAIL'

export const UPDATE_STAFF_REQUEST = 'UPDATE_STAFF_REQUEST'
export const UPDATE_STAFF_SUCCESS = 'UPDATE_STAFF_SUCCESS'
export const UPDATE_STAFF_FAIL = 'UPDATE_STAFF_FAIL'
