export const EXTRA_BUDGET_REQUEST = 'EXTRA_BUDGET_REQUEST'
export const EXTRA_BUDGET_SUCCESS = 'EXTRA_BUDGET_SUCCESS'
export const EXTRA_BUDGET_FAIL = 'EXTRA_BUDGET_FAIL'

export const EXTRA_STAFF_REQUEST = 'EXTRA_STAFF_REQUEST'
export const EXTRA_STAFF_SUCCESS = 'EXTRA_STAFF_SUCCESS'
export const EXTRA_STAFF_FAIL = 'EXTRA_STAFF_FAIL'
