export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const DPT_USERS_REQUEST = 'DPT_USERS_REQUEST'
export const DPT_USERS_SUCCESS = 'DPT_USERS_SUCCESS'
export const DPT_USERS_FAIL = 'DPT_USERS_FAIL'

export const ASSIGN_TASK_REQUEST = 'ASSIGN_TASK_REQUEST'
export const ASSIGN_TASK_SUCCESS = 'ASSIGN_TASK_SUCCESS'
export const ASSIGN_TASK_FAIL = 'ASSIGN_TASK_FAIL'

export const EDIT_TASK_REQUEST = 'EDIT_TASK_REQUEST'
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS'
export const EDIT_TASK_FAIL = 'EDIT_TASK_FAIL'

export const GET_ALL_TASKS_FOR_EVENT_REQUEST = 'GET_ALL_TASKS_FOR_EVENT_REQUEST'
export const GET_ALL_TASKS_FOR_EVENT_SUCCESS = 'GET_ALL_TASKS_FOR_EVENT_SUCCESS'
export const GET_ALL_TASKS_FOR_EVENT_FAIL = 'GET_ALL_TASKS_FOR_EVENT_FAIL'
